imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, build/_js/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 7.4
    tests:
        before:
            - make install
            - php artisan key:generate
        override:
            -
                command: "make phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "clover"
